version: '3.8'

services:
  score-redis:
    image: redis
    container_name: score-redis

  score-mysql:
    image: mysql:8
    container_name: score-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=iamroot
      - MYSQL_DATABASE=wise_database
      - MYSQL_USER=wiseuser
      - MYSQL_PASSWORD=wisepass
    volumes:
      - './docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d'
      - './data:/var/lib/mysql'

  score-api:
    image: wiseberkeley/wise-api-dev:v1
    container_name: score-api
    expose:
      - '5005'
    depends_on:
      - score-redis
      - score-mysql
    ports:
      - '5005:5005'
      - '8080:8080'
    volumes:
      - '../SCORE-API:/app'
    command: mvn spring-boot:run -Dspring-boot.run.jvmArguments="-Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=*:5005" -Dspring-boot.run.profiles=dockerdev

  score-client:
    image: wiseberkeley/wise-client-dev:latest
    container_name: score-client
    depends_on:
      - score-api
    ports:
      - '4200:4200'
    volumes:
      - '../SCORE-Client:/app'

  score-nginx:
    image: nginx:1.13
    container_name: score-nginx
    depends_on:
      - score-client
    ports:
      - '80:80'
    volumes:
      - '${PWD}/nginx/conf.d:/etc/nginx/conf.d'
